#!/usr/bin/env bash

set -euo pipefail

readonly TRAILER_TOKEN="Co-authored-by"
readonly USAGE="usage: git add-card  Show card in commit template
   or: git add-card <card>           Update card in commit template
   or: git co-author clear           Remove card from commit template"

main() {
  if [[ $# -eq 0 ]]; then
    show_trailers
  fi
}

show_trailers() {
  ensure_template_file
  print_trailers
  exit 0
}

ensure_template_file() {
  must_have_config "commit.template" "commit template is not configured

Example:
  git config --global commit.template '~/.git-commit-template'"

  template_file=$(git config commit.template)
  template_file="${template_file/#\~/$HOME}"  # Replace '~' with $HOME

  touch "$template_file"
}

print_trailers() {
  sed -n "/$TRAILER_TOKEN/p" "$template_file"
}
